version: ~> 1.0

addons:
  apt:
    packages:
      - hunspell
      - libhunspell-dev
      - hunspell-en-us

import:
  - silverstripe/silverstripe-travis-shared:config/provision/standard-jobs-range.yml
